CREATE TABLE DiscoveryBooking (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'en',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
