import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.product.deleteMany();
  await prisma.blogPost.deleteMany();

  const products = [
    { name: "Predator P3 Revo Shaft - Cobalt Blue", slug: "predator-p3-revo-cobalt-blue", description: "The Predator P3 features a stunning cobalt blue stained Curly Maple forearm and butt sleeve. Combined with the legendary Revo shaft, this cue delivers unmatched power and precision.", price: 1489, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-p3-cobalt.jpg\"]", featured: true },
    { name: "Predator P3 Revo Shaft - Burgundy", slug: "predator-p3-revo-burgundy", description: "Rich burgundy finish with Revo carbon fiber shaft for maximum low-deflection performance.", price: 1489, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-p3-burgundy.jpg\"]", featured: true },
    { name: "Predator P3 Revo Shaft - Natural", slug: "predator-p3-revo-natural", description: "Clean natural finish P3 with Revo shaft. Beautiful Curly Maple grain.", price: 1489, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-p3-natural.jpg\"]", featured: false },
    { name: "Predator P3 RACER - Black/Yellow", slug: "predator-p3-racer-black-yellow", description: "Bold racing-inspired design with Revo shaft.", price: 1389, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-p3-racer.jpg\"]", featured: false },
    { name: "Predator P3 - Classic Black", slug: "predator-p3-classic-black", description: "Timeless black P3 with premium 314 shaft.", price: 999, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-p3-black.jpg\"]", featured: false },
    { name: "Predator Throne3-1 - Birdseye Maple", slug: "predator-throne3-1-birdseye", description: "Flagship Throne3-1 with exquisite Birdseye Maple and Revo shaft.", price: 2229, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-throne3-1.jpg\"]", featured: true },
    { name: "Predator Throne3-2 - Dark Stain", slug: "predator-throne3-2-dark", description: "Dark wood stain with premium Birdseye Maple. Revo 12.4mm shaft.", price: 2129, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-throne3-2.jpg\"]", featured: true },
    { name: "Predator Throne3-3 - Maple/Ebony", slug: "predator-throne3-3-maple-ebony", description: "Stunning Maple and Ebony contrast with Revo shaft.", price: 2029, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-throne3-3.jpg\"]", featured: false },
    { name: "Predator Throne3-4 - Rosewood", slug: "predator-throne3-4-rosewood", description: "Rich Rosewood construction with Revo shaft.", price: 1829, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-throne3-4.jpg\"]", featured: false },
    { name: "Predator SP2 Revo - Ember", slug: "predator-sp2-revo-ember", description: "SP2 REVO in Ember finish with carbon fiber shaft.", price: 1149, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-sp2-ember.jpg\"]", featured: false },
    { name: "Predator SP2 Revo - Ice", slug: "predator-sp2-revo-ice", description: "Cool Ice finish SP2 with Revo shaft.", price: 1149, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-sp2-ice.jpg\"]", featured: false },
    { name: "Predator SP2 - Forest", slug: "predator-sp2-forest", description: "Forest green SP2 with 314 shaft.", price: 949, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-sp2-forest.jpg\"]", featured: false },
    { name: "Predator Sang Lee LE - Dragon", slug: "predator-sang-lee-le-dragon", description: "Limited Edition Sang Lee Dragon cue with Revo shaft.", price: 1859, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-sang-lee-dragon.jpg\"]", featured: true },
    { name: "Predator Sang Lee LE - Phoenix", slug: "predator-sang-lee-le-phoenix", description: "Limited Edition Sang Lee Phoenix with Revo shaft.", price: 1759, category: "Cues", brand: "Predator", images: "[\"/images/products/predator-sang-lee-phoenix.jpg\"]", featured: false },
    { name: "BC-16 Low-Deflection Cue", slug: "bc-16-low-deflection-cue", description: "Professional low-deflection cue with carbon fiber technology.", price: 620, category: "Cues", brand: "BC", images: "[\"/images/products/bc-16-cue.jpg\"]", featured: false },
    { name: "Sport 2 Playing Cue", slug: "sport-2-playing-cue", description: "Premium sport cue for competitive play.", price: 764, category: "Cues", brand: "Sport", images: "[\"/images/products/sport-2-cue.jpg\"]", featured: false },
    { name: "Mezz Hybrid Pro II Shaft", slug: "mezz-hybrid-pro-ii-shaft", description: "Acclaimed shaft combining maple with carbon technology. 11.75mm.", price: 369, category: "Shafts", brand: "Mezz", images: "[\"/images/products/mezz-hybrid-pro-ii.jpg\"]", featured: true },
    { name: "Predator Revo 12.4mm Shaft", slug: "predator-revo-12-4-shaft", description: "100% carbon fiber zero-deflection shaft. The gold standard.", price: 499, category: "Shafts", brand: "Predator", images: "[\"/images/products/predator-revo-shaft.jpg\"]", featured: true },
    { name: "Predator Revo 12.9mm Shaft", slug: "predator-revo-12-9-shaft", description: "Larger Revo shaft for more surface area.", price: 499, category: "Shafts", brand: "Predator", images: "[\"/images/products/predator-revo-129-shaft.jpg\"]", featured: false },
    { name: "Predator 314-3 Shaft", slug: "predator-314-3-shaft", description: "Classic 10-piece maple shaft.", price: 299, category: "Shafts", brand: "Predator", images: "[\"/images/products/predator-314-shaft.jpg\"]", featured: false },
    { name: "Aramith Premium Pool Ball Set", slug: "aramith-premium-pool-ball-set", description: "Professional phenolic resin ball set.", price: 199, category: "Balls", brand: "Aramith", images: "[\"/images/products/aramith-premium-set.jpg\"]", featured: true },
    { name: "Aramith Super Pro Ball Set", slug: "aramith-super-pro-ball-set", description: "Tournament-grade precision ball set.", price: 271, category: "Balls", brand: "Aramith", images: "[\"/images/products/aramith-super-pro.jpg\"]", featured: false },
    { name: "Aramith Standard Pool Ball Set", slug: "aramith-standard-pool-ball-set", description: "Quality balls at an accessible price.", price: 134, category: "Balls", brand: "Aramith", images: "[\"/images/products/aramith-standard.jpg\"]", featured: false },
    { name: "Aramith TV Tournament Ball Set", slug: "aramith-tv-tournament-ball-set", description: "Enhanced contrast for TV broadcasts.", price: 249, category: "Balls", brand: "Aramith", images: "[\"/images/products/aramith-tv-tournament.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Black/Grey - S/M", slug: "predator-second-skin-black-grey-sm", description: "Ultra-thin breathable glove. Left hand.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-black-grey.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Black/Grey - L/XL", slug: "predator-second-skin-black-grey-lxl", description: "Larger fit Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-black-grey-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Blue - S/M", slug: "predator-second-skin-blue-sm", description: "Blue Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-blue-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Blue - L/XL", slug: "predator-second-skin-blue-lxl", description: "L/XL blue Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-blue-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Red - S/M", slug: "predator-second-skin-red-sm", description: "Red Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-red-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Red - L/XL", slug: "predator-second-skin-red-lxl", description: "L/XL red Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-red-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Green - S/M", slug: "predator-second-skin-green-sm", description: "Dark green Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-green-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Green - L/XL", slug: "predator-second-skin-green-lxl", description: "L/XL green Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-green-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Purple - S/M", slug: "predator-second-skin-purple-sm", description: "Purple Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-purple-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Purple - L/XL", slug: "predator-second-skin-purple-lxl", description: "L/XL purple Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-purple-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Orange - S/M", slug: "predator-second-skin-orange-sm", description: "Orange Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-orange-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Orange - L/XL", slug: "predator-second-skin-orange-lxl", description: "L/XL orange Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-orange-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Yellow - S/M", slug: "predator-second-skin-yellow-sm", description: "Yellow Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-yellow-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Yellow - L/XL", slug: "predator-second-skin-yellow-lxl", description: "L/XL yellow Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-yellow-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - White - S/M", slug: "predator-second-skin-white-sm", description: "White Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-white-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - White - L/XL", slug: "predator-second-skin-white-lxl", description: "L/XL white Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-white-lxl.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Pink - S/M", slug: "predator-second-skin-pink-sm", description: "Pink Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-pink-sm.jpg\"]", featured: false },
    { name: "Predator Second Skin Glove - Pink - L/XL", slug: "predator-second-skin-pink-lxl", description: "L/XL pink Second Skin glove.", price: 29, category: "Gloves", brand: "Predator", images: "[\"/images/products/predator-glove-pink-lxl.jpg\"]", featured: false },
    { name: "Buffalo Billiard Glove - Left Hand", slug: "buffalo-glove-black-left", description: "Affordable three-finger billiard glove.", price: 17.99, category: "Gloves", brand: "Buffalo", images: "[\"/images/products/buffalo-glove-black.jpg\"]", featured: false },
    { name: "Buffalo Billiard Glove - Right Hand", slug: "buffalo-glove-black-right", description: "Right-hand billiard glove.", price: 17.99, category: "Gloves", brand: "Buffalo", images: "[\"/images/products/buffalo-glove-black-right.jpg\"]", featured: false },
    { name: "Predator Urbain 2x4 Hard Case", slug: "predator-urbain-2x4-hard-case", description: "Premium case for 2 butts and 4 shafts.", price: 189, category: "Cases", brand: "Predator", images: "[\"/images/products/predator-urbain-case.jpg\"]", featured: false },
    { name: "Standard 1x1 Soft Cue Case", slug: "standard-1x1-soft-case-black", description: "Basic soft case with shoulder strap.", price: 12.49, category: "Cases", brand: "Standard", images: "[\"/images/products/soft-case-1x1.jpg\"]", featured: false },
    { name: "Standard 1x1 Hard Cue Case", slug: "standard-1x1-hard-case-blue", description: "Durable hard shell case.", price: 24.99, category: "Cases", brand: "Standard", images: "[\"/images/products/hard-case-1x1-blue.jpg\"]", featured: false },
    { name: "Standard 2x2 Soft Cue Case", slug: "standard-2x2-soft-case", description: "Holds two butts and two shafts.", price: 19.99, category: "Cases", brand: "Standard", images: "[\"/images/products/soft-case-2x2.jpg\"]", featured: false },
    { name: "Dominator 9ft Professional Pool Table", slug: "dominator-9ft-pool-table", description: "Tournament 9ft table with Italian slate. Includes installation.", price: 3700, category: "Tables", brand: "Dominator", images: "[\"/images/products/dominator-9ft.jpg\"]", featured: true },
    { name: "Europool Cloth 9ft - Blue", slug: "europool-cloth-9ft-blue", description: "Professional worsted cloth.", price: 150, category: "Accessories", brand: "Europool", images: "[\"/images/products/europool-cloth-blue.jpg\"]", featured: false },
    { name: "Europool Cloth 9ft - Green", slug: "europool-cloth-9ft-green", description: "Classic green tournament cloth.", price: 150, category: "Accessories", brand: "Europool", images: "[\"/images/products/europool-cloth-green.jpg\"]", featured: false },
    { name: "Predator 1080 Pure Chalk - 5 Pack", slug: "predator-1080-pure-chalk-5pack", description: "Premium performance chalk.", price: 39.99, category: "Accessories", brand: "Predator", images: "[\"/images/products/predator-chalk.jpg\"]", featured: false },
    { name: "Kamui Roku Chalk", slug: "kamui-roku-chalk", description: "Ultra-premium Japanese chalk.", price: 29.99, category: "Accessories", brand: "Kamui", images: "[\"/images/products/kamui-roku-chalk.jpg\"]", featured: false },
    { name: "Master Chalk Blue - 12 Pack", slug: "master-chalk-blue-12pack", description: "Classic trusted chalk.", price: 8.99, category: "Accessories", brand: "Master", images: "[\"/images/products/master-chalk.jpg\"]", featured: false },
    { name: "Kamui Black Tip - Medium 14mm", slug: "kamui-black-tip-medium-14mm", description: "Premium Japanese layered tip.", price: 24.99, category: "Accessories", brand: "Kamui", images: "[\"/images/products/kamui-black-tip.jpg\"]", featured: false },
    { name: "Predator Victory Tip - Medium 14mm", slug: "predator-victory-tip-medium-14mm", description: "8-layer premium pigskin tip.", price: 19.99, category: "Accessories", brand: "Predator", images: "[\"/images/products/predator-victory-tip.jpg\"]", featured: false },
    { name: "Shaft Cleaner & Conditioner", slug: "shaft-cleaner-conditioner", description: "Professional shaft maintenance.", price: 12.99, category: "Accessories", brand: "Q-Wiz", images: "[\"/images/products/shaft-cleaner.jpg\"]", featured: false },
    { name: "Tip Shaper & Scuffer", slug: "tip-shaper-scuffer-tool", description: "Multi-function tip tool.", price: 9.99, category: "Accessories", brand: "Willard", images: "[\"/images/products/tip-shaper.jpg\"]", featured: false },
    { name: "Magnetic Chalk Holder - Gold", slug: "magnetic-chalk-holder-gold", description: "Gold magnetic chalk holder.", price: 14.99, category: "Accessories", brand: "Standard", images: "[\"/images/products/chalk-holder-gold.jpg\"]", featured: false },
    { name: "Joint Protector Set", slug: "joint-protector-set-black", description: "Protect your cue joints.", price: 16.99, category: "Accessories", brand: "Standard", images: "[\"/images/products/joint-protectors.jpg\"]", featured: false },
    { name: "9BallShop T-Shirt - Black", slug: "9ballshop-tshirt-black", description: "Premium cotton tee with logo.", price: 34.99, category: "Apparel", brand: "9BallShop", images: "[\"/images/products/9ballshop-tshirt.jpg\"]", featured: false },
    { name: "9BallShop Polo - Navy", slug: "9ballshop-polo-navy", description: "Professional polo shirt.", price: 49.99, category: "Apparel", brand: "9BallShop", images: "[\"/images/products/9ballshop-polo.jpg\"]", featured: false },
    { name: "9BallShop Cap - Black/Gold", slug: "9ballshop-cap-black-gold", description: "Snapback cap with gold embroidery.", price: 24.99, category: "Apparel", brand: "9BallShop", images: "[\"/images/products/9ballshop-cap.jpg\"]", featured: false },
  ];

  for (const p of products) {
    await prisma.product.create({ data: p });
  }
  console.log("Seeded " + products.length + " products");

  const blogPosts = [
    { title: "7 Ways to Mentally Prepare for a High Performance Activity", slug: "7-ways-mentally-prepare-high-performance", excerpt: "Mental preparation is the difference between good and great. Here are 7 proven strategies.", content: "# 7 Ways to Mentally Prepare\n\n## 1. Visualization\nBefore any big match, I spend 15-20 minutes visualizing every aspect of the game.\n\n## 2. Controlled Breathing\nBox breathing: inhale for 4 seconds, hold for 4, exhale for 4, hold for 4.\n\n## 3. Pre-Performance Routine\nDevelop a consistent routine that triggers your performance mindset.\n\n## 4. Positive Self-Talk\nReplace negative thoughts with constructive ones.\n\n## 5. Focus on Process, Not Outcome\nFocus on executing each moment, not on the score.\n\n## 6. Embrace the Pressure\nPressure is a privilege. Reframe it as excitement.\n\n## 7. Mental Rehearsal of Adversity\nPrepare for things going wrong. Have a mental plan.", coverImage: "/images/blog/mental-preparation.jpg", tags: "[\"Performance\",\"Mental Game\",\"Competition\",\"Mindset\"]", mediumUrl: "https://medium.com/@marioskomninakis", publishedAt: new Date("2024-03-15") },
    { title: "Gambling Addiction: How I Got Hooked and the 7 Things I Did to Quit", slug: "gambling-addiction-how-i-got-hooked", excerpt: "My honest story about gambling addiction and the 7 steps to break free.", content: "# Gambling Addiction\n\nI was 19 when I started playing pool for money. The rush was intoxicating.\n\n## The 7 Things I Did to Quit\n\n### 1. Admitted the Problem\n### 2. Cut Off Access\n### 3. Found Professional Help\n### 4. Replaced the Rush\n### 5. Built an Accountability Circle\n### 6. Developed Financial Discipline\n### 7. Practiced Daily Reflection\n\nRecovery isn't a destination - it's a daily choice.", coverImage: "/images/blog/gambling-addiction.jpg", tags: "[\"Personal Story\",\"Addiction\",\"Recovery\",\"Life Lessons\"]", mediumUrl: "https://medium.com/@marioskomninakis", publishedAt: new Date("2024-01-22") },
    { title: "How to Build Discipline Through Rewarding Yourself", slug: "build-discipline-through-rewarding-yourself", excerpt: "Strategic self-rewards build ironclad habits.", content: "# How to Build Discipline Through Rewarding Yourself\n\nReal, sustainable discipline is built on strategic rewards.\n\n## The Reward Framework\n\n### Micro-Rewards (Daily)\nSmall rewards for completing significant tasks.\n\n### Meso-Rewards (Weekly)\nBigger treats when you hit all your weekly targets.\n\n### Macro-Rewards (Monthly/Quarterly)\nCelebrate major goal achievements properly.\n\nThe rewards bridge you from 'I have to' to 'I get to.'", coverImage: "/images/blog/discipline-rewards.jpg", tags: "[\"Discipline\",\"Habits\",\"Self-Improvement\",\"Mindset\"]", mediumUrl: "https://medium.com/@marioskomninakis", publishedAt: new Date("2024-05-10") },
    { title: "How Communication Skills Will Help You Achieve Mastery", slug: "communication-skills-achieve-mastery", excerpt: "The secret weapon of masters isn't just talent - it's communication.", content: "# How Communication Skills Will Help You Achieve Mastery\n\nCommunication is the multiplier that accelerates everything.\n\n## Why Communication Matters\n\n### Learning from Masters\nAsk the right questions. Show respect for their time.\n\n### Teaching What You Know\nTeaching forces deeper understanding.\n\n### Building Your Network\nAll relationships are built on communication.\n\n### Self-Communication\nThe most important conversations are with yourself.\n\nCommunication skills compound over time.", coverImage: "/images/blog/communication-mastery.jpg", tags: "[\"Communication\",\"Mastery\",\"Self-Improvement\",\"Career\"]", mediumUrl: "https://medium.com/@marioskomninakis", publishedAt: new Date("2024-06-18") },
    { title: "How I Went from Greece to USA Without Money or Connections", slug: "greece-to-usa-without-money-or-connections", excerpt: "The raw story of leaving Greece with nothing and building a new life.", content: "# How I Went from Greece to USA Without Money or Connections\n\nI was 21, living in Athens with 800 euros and a pool cue.\n\n## The First Weeks\nLanding in New York was terrifying and exhilarating.\n\n## Building from Zero\nThe pool community embraced me. I hustled, worked side jobs, and practiced every day.\n\n## Lessons\n1. **Resourcefulness Beats Resources**\n2. **Skill Is Universal Currency**\n3. **Community Is Everything**\n4. **Comfort Is the Enemy**\n5. **The Story Isn't Over**\n\nTake the shot.", coverImage: "/images/blog/greece-to-usa.jpg", tags: "[\"Personal Story\",\"Immigration\",\"Entrepreneurship\",\"Motivation\"]", mediumUrl: "https://medium.com/@marioskomninakis", publishedAt: new Date("2024-02-28") },
    { title: "I Read All Robert Greene's Books - 5 Most Crucial Things I Learnt", slug: "robert-greene-books-5-crucial-lessons", excerpt: "5 lessons from Robert Greene that changed how I approach life.", content: "# I Read All Robert Greene's Books\n\n## 1. Mastery Requires Deep, Deliberate Practice\nFrom **Mastery**: True mastery goes beyond 10,000 hours.\n\n## 2. Never Outshine the Master\nFrom **48 Laws of Power**: Make those above you feel valued.\n\n## 3. Understand People's True Motivations\nFrom **Laws of Human Nature**: Watch behavior, not words.\n\n## 4. Turn Obstacles into Advantages\nFrom **33 Strategies of War**: Every disadvantage can become an edge.\n\n## 5. Play the Long Game\nThink 5-10 years ahead, not next month.\n\nKnowledge without application is just entertainment.", coverImage: "/images/blog/robert-greene.jpg", tags: "[\"Books\",\"Self-Improvement\",\"Power\",\"Strategy\"]", mediumUrl: "https://medium.com/@marioskomninakis", publishedAt: new Date("2024-04-12") },
    { title: "5 Habits to Unlock 100% of Your Brain", slug: "5-habits-unlock-100-percent-brain", excerpt: "Science-backed habits that optimize cognitive performance.", content: "# 5 Habits to Unlock 100% of Your Brain\n\n## 1. Sleep Is Non-Negotiable\n7-8 hours of quality sleep transforms performance.\n\n## 2. Exercise Your Body to Upgrade Your Brain\nExercise increases BDNF and grows new brain cells.\n\n## 3. Feed Your Brain Properly\nOmega-3s, blueberries, nuts, leafy greens, eggs.\n\n## 4. Practice Deep Focus Daily\nStart with 25-minute Pomodoro blocks, build to 90 minutes.\n\n## 5. Learn Something New Constantly\nVariety matters as much as volume.\n\nYour brain is the most powerful tool you have.", coverImage: "/images/blog/unlock-brain.jpg", tags: "[\"Health\",\"Performance\",\"Habits\",\"Self-Improvement\"]", mediumUrl: "https://medium.com/@marioskomninakis", publishedAt: new Date("2024-07-05") },
  ];

  for (const post of blogPosts) {
    await prisma.blogPost.create({ data: post });
  }
  console.log("Seeded " + blogPosts.length + " blog posts");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
